name: OrangeHRM Selenium CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Firefox and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb

      - name: Run tests
        env:
          CI: true
        run: xvfb-run -a mvn clean test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: orangehrm-test-report
          path: |
            test-output/
            target/surefire-reports/